# Generated by Django 6.0.3 on 2026-04-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('quiere_camisa', models.BooleanField(default=False)),
                ('talla_camisa', models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5, null=True)),
                ('precio_camisa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('NIO', 'Córdobas')], default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='campamento.campista')),
            ],
        ),
    ]
