# Generated by Django 6.0.3 on 2026-04-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campista',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='campista',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='campista',
            name='precio_camisa',
        ),
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('NIO', 'Córdobas')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campista',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
