# Generated by Django 6.0.3 on 2026-04-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campamento', '0003_campista_subsidizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campista',
            name='talla_camisa',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True),
        ),
    ]
